### ISSUE TITLE
[VIRUS] GOP_Updater

### ISSUE THREAD

**Issue by Lar-Sen** [YTEC-info/GOP_Updater#1]
GOPupd.exe is infected. It drops a troyan named w32.gosys.

Not really hard to erase if fixed in time, as it replicates quite fast.

**Comment by Lar-Sen** [comment]
I have to correct myself. Remote analysis proves that this file is actually safe.
I need to find what I did before downloading GOPupdater... as the worm Swisyn.BNER self injects itself in each .exe file in the directory of the infected .exe, at first.

So no issue there :)

**Comment by YTEC-info** [comment]
No problem, there is no virus here. Anyway, for security reasons I only use virtualized Windows, away from my personal files that are on the Linux that I use daily.
