### ISSUE TITLE
[VIRUS] Do not run this file it contains Virus Replicates quite fast

### ISSUE THREAD

**Issue by crypticrad** [YTEC-info/GOP_Updater#2]

**Comment by YTEC-info** [comment]
Is this what some antivirus said or did you do some in-depth study of the files?

This repository contains programs that modify the GPU firmware, by changing this sensitive part it is obvious that any stupid antivirus will give several warnings

**Comment by linuxuser2064** [comment]
this program ran a fake explorer.exe in C:\Windows\System. windows defender picked it up but take this the fuck down.
